ex05fourier all:
	g++ *.cpp -g -I/opt/local/include -L/opt/local/lib  -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -o ex05fourier
clean:
	rm -f ex05fourier
run: clean all
	./ex05fourier
